Repository 0xTheProDev/Operational-Transformation, pull requests merged in 2021-10, with the labels that each got.

#56 Added Code of Conduct
  .github/CODE_OF_CONDUCT.md
Labels: Hacktoberfest

#57 Readme: Added Contributing Guidelines
  .github/CONTRIBUTING.md
  .github/images/Issues.jpeg
  .github/images/PR.jpeg
  .github/images/PullRequest.jpeg
Labels: v0.2.0, Hacktoberfest

#58 FIX: Update Contributing.md
  .github/CONTRIBUTING.md
Labels: Hacktoberfest

#62 (fix) Monaco Adapter: Cleanup ClassName Logic for Remote Cursor
  __tests__/monaco/__tests__/monaco-adapter.spec.ts
  packages/monaco/src/monaco-adapter.ts
Labels: v0.2.0, Hacktoberfest

#65 (docs) Contributing Guidelines: Update CONTRIBUTING markdown file
  .github/CONTRIBUTING.md
Labels: v0.2.0

#69 (docs) Readme: Update Peer Dependency Table
  README.md
  packages/ace/README.md
  packages/firebase-ace/README.md
  packages/firebase-plaintext/README.md
  packages/monaco/README.md
  packages/plaintext-editor/README.md
Labels: v0.2.0

#71 (docs) Examples: Update collaborative-editors README file
  .github/images/examples/collaborative-editors/FirebaseMonaco.png
  .github/images/examples/collaborative-editors/LandingPage.png
  examples/collaborative-editors/README.md
Labels: v0.2.0, Hacktoberfest

#74 (docs) Packages: Add Stargazer Count in Package Readme
  packages/ace/README.md
  packages/firebase-ace/README.md
  packages/firebase-monaco/README.md
  packages/firebase-plaintext/README.md
  packages/monaco/README.md
  packages/plaintext-editor/README.md
  packages/plaintext/README.md
  packages/state-machine/README.md
Labels: v0.2.0

#75 (feat) @otjs/ace: Add remote cursor/selection to Ace
  packages/ace/src/ace-adapter.ts
  packages/utils/__tests__/__snapshots__/styles.spec.ts.snap
  packages/utils/src/styles.ts
Labels: v0.2.0
